
AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Description: husky shelters web app
Resources:
  GetPets:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getAllPets
      Handler: pets.getAllPets
      Runtime: python3.8
      CodeUri: package/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PetsTable
      Environment:
        Variables:
          PETS_TABLE: !Ref PetsTable
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: "/"
            Method: GET
  
  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: husky-shelters-web-app-api2
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml

  PetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: husky-shelters-web-app2
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: Name
          AttributeType: S
        - AttributeName: HealthStatus
          AttributeType: S
        - AttributeName: Age
          AttributeType: S
        - AttributeName: Location
          AttributeType: S
      LocalSecondaryIndexes: 
        - IndexName: NameLSI
          KeySchema: 
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: Name
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: HealthStatusLSI
          KeySchema: 
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: HealthStatus
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: AgeLSI
          KeySchema: 
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: Age
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: LocationLSI
          KeySchema: 
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: Location
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          
          
  

